FROM node as build 

WORKDIR /app 

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build 

EXPOSE 3000 

FROM  nginx:latest 

COPY --from=build ./build  /usr/share/nginx/html 
COPY nginx/opl-front-dev.conf /etc/nginx/conf.d/opl-front-dev.conf

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]

