FROM node:16

WORKDIR /app 

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm run build 

EXPOSE 3000 

FROM  nginx:latest 

COPY --from=build ./build /usr/share/nginx/html

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]


